version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: todo-password
      MYSQL_DATABASE: todo
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  go:
    image: todo-api
    container_name: todo-api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mysql-data: